blank_issues_enabled: false
contact_links:
  - name: Questions sur Patrimoine360 Core
    url: https://github.com/SREWA-DIGITAL/PATRIMOINE360-CORE/discussions
    about: Poser une question ou partager une idée avec la communauté.
  - name: Signalement de sécurité
    url: https://github.com/SREWA-DIGITAL/PATRIMOINE360-CORE/security/advisories/new
    about: Signaler une vulnérabilité de manière privée.
